### ISSUE TITLE
Alignment of images

### ISSUE THREAD

**Issue by mike-weaver** [ocelotconsulting/ocelotconsulting.github.io#155]
Probably not a huge deal right now as we will start swapping out a lot of the images in May when we get our summer intern, but you will notice a big difference in the alignment of the image from the Fluid22 original version to the current prod version...

![Screenshot 2023-04-28 at 8 28 28 AM](https://user-images.githubusercontent.com/48367929/235160961-af7819e3-73e8-4efa-b649-f19ef5f23c5d.png)

![Screenshot 2023-04-28 at 8 28 19 AM](https://user-images.githubusercontent.com/48367929/235160990-4c91ca99-acac-4876-b58c-6ed85cf10569.png)

**Comment by nerddtvg** [comment]
There are a few pages where I see this:

- https://www.ocelotconsulting.com/services/data-engineering (from Mike's example)
- https://www.ocelotconsulting.com/services/cloud-transformation (lady smiling)
- https://www.ocelotconsulting.com/services/full-stack-development (two people smiling)
- https://www.ocelotconsulting.com/services/data-science (lady smiling)
- https://www.ocelotconsulting.com/services/strategy-execution (man smiling)

It seems to be that third section of the strategy pages, I'm guessing because they were copied and pasted. It just depends on how much you want the focus to be on the images. We could maybe re-crop the high-five image to make it slightly better without a CSS change.

Changing from `bg-center` to `bg-left` brings the image back into frame, but on some (very specific edge cases) devices, it may appear worse:

Width: 1074 `bg-left`
![image](https://user-images.githubusercontent.com/5490719/235473932-72301c70-6499-42fa-ba35-8787a8f57491.png)

Width: 1074 `bg-center`
![image](https://user-images.githubusercontent.com/5490719/235474013-73379129-0b4b-410c-9635-6e7d40008572.png)
