### ISSUE TITLE
Create a netlify.com proof of concept

### ISSUE THREAD

**Issue by Techneaux** [ocelotconsulting/ocelotconsulting.github.io#73]
Create a mirror deploy to netlify free tier. Share with team any benefits over current deploy e.g. site previews during PRs. Goal: are benefits from netlify worth the extra complexity?

**Comment by nerddtvg** [comment]
@Techneaux I was able to quickly setup the Netlify free tier against my private repo. Works well and out of the box with no customizations required.

**Comment by nerddtvg** [comment]
I'm reviving this request from last year. I just sent a request to install the Netlify app for the ocelotconsulting.github.io repository only.

**Comment by nerddtvg** [comment]
Using PR #99, I was able to trigger a build automatically. If the build fails for any reason, the PR cannot be merged until fixed.

![image](https://user-images.githubusercontent.com/5490719/126655982-372deb8e-3e1c-4fc7-9e3f-6dba69a5731c.png)

A successful build links to the preview site: https://deploy-preview-99--romantic-austin-f85522.netlify.app/

Recommendations to move forward:

* Designate a small Netlify team, keeps costs down (Pro plan [$15/member/month] required)
* Consider upgrading to Pro to enable password protection on the site (previews and "production" Netlify would require a password)
* Consider using JWTs to protect the site and implementing [GitHub OAuth](https://docs.netlify.com/visitor-access/oauth-provider-tokens/) if that is possible for preview builds so that only Ocelot GitHub users can access the builds
* Consider having multiple Netlify Owners (Pro plan required) to protect being locked out
  * Alternative: Create a shared @ocelotconsulting.com account to set the owner to for protection
* Consider Netlify SSO (Business plan [$99/member/month] required) to tie Azure AD to Netlify instead of having local accounts to manage

The access restrictions are to prevent extra SEO scraping mostly since all PRs and codebases are public. If those were private, it would allow for testing announcements privately as well.

**Comment by nerddtvg** [comment]
I should also point out that previews are forever. They're not auto-deleted and cannot be manually deleted when the PR is closed. This is a feature request. At this time I don't see that as a concern.

https://answers.netlify.com/t/does-each-deploy-preview-stay-available-forever/12601/24
